const basePath = '/01-Java基础/learn/'

export default {
  text: 'Java简明教程',
  collapsed: false,
  items: [
    { text: 'Java基础-类与构造器', link: basePath + 'Java基础-类与构造器' },
    { text: 'Java基础-this关键字', link: basePath + 'Java基础-this关键字' },
    { text: 'Java基础-super关键字', link: basePath + 'Java基础-super关键字' },
    { text: 'Java基础-static关键字', link: basePath + 'Java基础-static关键字' },
    { text: 'Java基础-成员变量、局部变量', link: basePath + 'Java基础-成员变量、局部变量' },
    { text: 'Java基础-抽象类、方法', link: basePath + 'Java基础-抽象类、方法' },
    { text: 'Java基础-接口', link: basePath + 'Java基础-接口' },
    { text: 'Java基础-包装类与自动装箱', link: basePath + 'Java基础-包装类与自动装箱' },
    { text: 'Java基础-自动装箱', link: basePath + 'Java基础-自动装箱' },
    { text: 'Java基础-final关键字', link: basePath + 'Java基础-final关键字' },
    { text: 'Java基础-JavaBean', link: basePath + 'Java基础-JavaBean' },
    { text: 'Java基础-interface关键字', link: basePath + 'Java基础-interface关键字' },
    { text: 'Java基础-native关键字', link: basePath + 'Java基础-native关键字' },
    { text: 'Java基础-foreach', link: basePath + 'Java基础-foreach' },
    { text: 'Java基础-Iterator 与 Iterable', link: basePath + 'Java基础-Iterator 与 Iterable' },
    { text: 'Java基础-Junit单元测试', link: basePath + 'Java基础-Junit单元测试' },
    { text: 'Java基础-泛型', link: basePath + 'Java基础-泛型' },
    { text: 'Java基础-枚举类', link: basePath + 'Java基础-枚举类' },
    { text: 'Java基础-内部类', link: basePath + 'Java基础-内部类' },
    { text: 'Java基础-注解', link: basePath + 'Java基础-注解' },
    { text: 'Java基础-反射', link: basePath + 'Java基础-反射' },
    { text: 'Java基础-异常', link: basePath + 'Java基础-异常' },
    { text: 'Java常用类-Object类', link: basePath + 'Java常用类-Object类' },
    { text: 'Java常用类-System类', link: basePath + 'Java常用类-System类' },
    { text: 'Java常用类-String-StringBuffer-StringBuilder', link: basePath + 'Java常用类-String-StringBuffer-StringBuilder' },
    { text: 'Java常用类-日期时间相关', link: basePath + 'Java常用类-日期时间相关' },
    { text: 'Java常用类-数学相关', link: basePath + 'Java常用类-数学相关' },
    { text: 'Java工具类-Arrays', link: basePath + 'Java工具类-Arrays' },
    { text: 'Java工具类-Collections', link: basePath + 'Java工具类-Collections' },
    { text: 'Java-集合框架', link: basePath + 'Java-集合框架' },
    { text: 'Java-IO流', link: basePath + 'Java-IO流' },
    { text: 'Java-多线程基础', link: basePath + 'Java-多线程基础' },
    { text: 'Jdk8-新特性', link: basePath + 'Jdk8-新特性' },

    { text: 'Java比较器-Comparable-Comparator', link: basePath + 'Java比较器-Comparable-Comparator' },

    { text: 'Java编码解码', link: basePath + 'Java编码解码' },
    { text: 'Java-Lombok', link: basePath + 'Java-Lombok' },
    { text: '读取配置文件properties的方式', link: basePath + '读取配置文件properties的方式' },
    { text: 'Typesafe配置库Config', link: basePath + 'Typesafe配置库Config' },
  ]
}